apiVersion: v1
kind: Service
metadata:
  name: rebom-frontend-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: rebom
    name: rebom-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

